# import = ["/Users/sergio.correa/.config/alacritty/nordic/nordic.toml"]
import = ["/Users/sergio.correa/.config/alacritty/gruvbox/gruvbox-material-dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.bold]
family = "Operator Mono"
style = "Book Bold"

[font.bold_italic]
family = "Operator Mono"
style = "Bold Italic"

[font.italic]
family = "Operator Mono"
style = "Book Italic"

[font.normal]
family = "Operator Mono"
style = "Book"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
opacity = 0.9
decorations = "buttonless"

[window.padding]
x = 20
y = 10

[window.dimensions]
columns = 240
lines = 80
