import:
 # - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
 # - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
 # - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
 # - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
 # - ~/.config/alacritty/gruvbox/gruvbox-dark.yml
 # - ~/.config/alacritty/gruvbox/gruvbox-material-dark.yml
 # - ~/.config/alacritty/gotham/gotham.yml
 - ~/.config/alacritty/rose-pine/rose-pine-moon.yml
 # - ~/.config/alacritty/rose-pine/rose-pine.yml

font:
  size: 14
  normal:
    family: Lilex Nerd Font
    style: Regular

key_bindings:
  - { key: Q, mods: Control, chars: "\x11" }
  - { key: Slash, mods: Control, chars: "\x1f" }

window:
  startup_mode: SimpleFullscreen
  opacity: 0.9
  padding:
    y: 10
    x: 20
  dynamic_padding: true

